CREATE TABLE stock (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, sku VARCHAR(255) NOT NULL, stock INT NOT NULL, UNIQUE INDEX UNIQ_4B365660F9038C4 (sku), UNIQUE INDEX UNIQ_4B3656604584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
ALTER TABLE stock ADD CONSTRAINT FK_4B3656604584665A FOREIGN KEY (product_id) REFERENCES products (id);
ALTER TABLE products ADD short_desc LONGTEXT NOT NULL, DROP shortDesc, DROP stock, CHANGE sku sku VARCHAR(255) NOT NULL, CHANGE ean ean VARCHAR(255) DEFAULT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE manufacturer manufacturer VARCHAR(255) NOT NULL, CHANGE price price NUMERIC(10, 2) NOT NULL;
CREATE UNIQUE INDEX UNIQ_B3BA5A5AF9038C4 ON products (sku);
